{
    "openapi": "3.0.0",
    "info": {
        "title": "Library Management API",
        "version": "1.0.0",
        "description": "API documentation for managing library system"
    },
    "servers": [
        {
            "url": "http://localhost:3000"
        }
    ],
    "tags": [
        {
            "name": "Auth",
            "description": "API for auth in the system"
        },
        {
            "name": "Books",
            "description": "API for books in the system"
        },
        {
            "name": "Borrowers",
            "description": "API for URL borrowers in the system"
        },
        {
            "name": "Borrowings",
            "description": "API for borrowings in the system"
        }
    ],
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Log in",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Login"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User logged in successfully",
                        "schema": {
                            "type": "object",
                            "content": {
                                "application/json": {
                                    "example": {
                                        "data": {
                                            "borrower": {
                                                "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                                "name": "John Doe",
                                                "email": "john.doe@example.com",
                                                "createdAt": "2024-01-11T12:00:00Z"
                                            },
                                            "token": "Your_token"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "email is required"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "invalid email or password"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/books": {
            "post": {
                "tags": [
                    "Books"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Create a new book",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Book"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Book created successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "title": "Sample Book",
                                        "author": "John Doe",
                                        "ISBN": "1234567890",
                                        "availableQuantity": 10,
                                        "shelfLocation": "A1"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "ISBN already exists"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Books"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get all books",
                "parameters": [
                    {
                        "name": "title",
                        "in": "query",
                        "description": "Search by title partially",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "ISBN",
                        "in": "query",
                        "description": "Search by ISBN",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "author",
                        "in": "query",
                        "description": "Search by author",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "description": "Defaults to 1.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Defaults to 20.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of books",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "count": 10,
                                        "rows": [
                                            {
                                                "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                                "title": "Sample Book",
                                                "author": "John Doe",
                                                "ISBN": "1234567890",
                                                "availableQuantity": 10,
                                                "shelfLocation": "A1"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "tags": [
                    "Books"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get a book by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book details",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "title": "Sample Book",
                                        "author": "John Doe",
                                        "ISBN": "1234567890",
                                        "availableQuantity": 10,
                                        "shelfLocation": "A1"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Book not found"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Books"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Update a book by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Book"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Book updated successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "title": "Updated Book",
                                        "author": "John Doe",
                                        "ISBN": "1234567890",
                                        "availableQuantity": 10,
                                        "shelfLocation": "A1"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid data"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Book not found"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Books"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Delete a book by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book deleted successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "message": "Book deleted successfully"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Book not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowers": {
            "post": {
                "tags": [
                    "Borrowers"
                ],
                "summary": "Create a new borrower",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Borrower"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Borrower created successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "name": "John Doe",
                                        "email": "john.doe@example.com",
                                        "createdAt": "2024-01-11T12:00:00Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Email already exists"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get all borrowers",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "Search by name partially",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "email",
                        "in": "query",
                        "description": "Search by email",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "description": "Defaults to 1.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Defaults to 20.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of borrowers",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "count": 10,
                                        "rows": [
                                            {
                                                "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                                "name": "John Doe",
                                                "email": "john.doe@example.com",
                                                "createdAt": "2024-01-11T12:00:00Z",
                                                "updatedAt": "2024-01-11T12:00:00Z"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowers/{id}": {
            "get": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get a borrower by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Borrower details",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "name": "John Doe",
                                        "email": "john.doe@example.com",
                                        "createdAt": "2024-01-11T12:00:00Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Update a borrower by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Borrower"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Borrower updated successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "name": "Updated John Doe",
                                        "email": "john.doe@example.com",
                                        "createdAt": "2024-01-11T12:00:00Z"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid data"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Delete a borrower by ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Borrower deleted successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "message": "Borrower deleted successfully"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowers/{id}/books/borrow_books": {
            "post": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Borrow books for a borrower",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "booksIds": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "dueDate": {
                                        "type": "string",
                                        "format": "date-time"
                                    }
                                },
                                "required": [
                                    "booksIds",
                                    "dueDate"
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Books borrowed successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "message": "Books borrowed successfully"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowers/{id}/books/return_books": {
            "put": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Return books for a borrower",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "booksIds": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "required": [
                                    "booksIds"
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Books returned successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "message": "Books borrowed successfully"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowers/{id}/books/current_books": {
            "get": {
                "tags": [
                    "Borrowers"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get books for a borrower",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "borrowed, returned, all, overdue. Defaults to borrowed.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "borrowed",
                                "returned",
                                "all",
                                "overdue"
                            ]
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "description": "Defaults to 1.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Defaults to 20.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of books for a borrower",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "count": 10,
                                        "rows": [
                                            {
                                                "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                                "checkoutDate": "2024-01-09T23:15:19.780Z",
                                                "returnDate": null,
                                                "dueDate": "2024-01-09T23:20:59.883Z",
                                                "book": {
                                                    "id": "a8d8201a-af2e-4714-94af-2addc78f6a95",
                                                    "title": "book 3",
                                                    "author": "Esraa",
                                                    "ISBN": "3"
                                                },
                                                "borrower": {
                                                    "id": "27b68ba2-dde6-49a5-bf7d-44352960da5e",
                                                    "name": "user 1",
                                                    "email": "user1@test.com"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrower not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrower not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowings": {
            "get": {
                "tags": [
                    "Borrowings"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get all borrowings",
                "parameters": [
                    {
                        "name": "status",
                        "in": "query",
                        "description": "borrowed, returned, all, overdue. Defaults to borrowed.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "borrowed",
                                "returned",
                                "all",
                                "overdue"
                            ]
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "description": "Defaults to 1.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Defaults to 20.",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of borrowings",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "count": 10,
                                        "rows": [
                                            {
                                                "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                                "checkoutDate": "2024-01-09T23:15:19.780Z",
                                                "returnDate": null,
                                                "dueDate": "2024-01-09T23:20:59.883Z",
                                                "book": {
                                                    "id": "a8d8201a-af2e-4714-94af-2addc78f6a95",
                                                    "title": "book 3",
                                                    "author": "Esraa",
                                                    "ISBN": "3"
                                                },
                                                "borrower": {
                                                    "id": "27b68ba2-dde6-49a5-bf7d-44352960da5e",
                                                    "name": "user 1",
                                                    "email": "user1@test.com"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowings/{id}": {
            "get": {
                "tags": [
                    "Borrowings"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get a borrowing by ID",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "Borrowing details",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "id": "f1ad5f6d-4295-495e-8cb4-334c4dd44e9f",
                                        "checkoutDate": "2024-01-09T23:15:19.780Z",
                                        "returnDate": null,
                                        "dueDate": "2024-01-09T23:20:59.883Z",
                                        "book": {
                                            "id": "a8d8201a-af2e-4714-94af-2addc78f6a95",
                                            "title": "book 3",
                                            "author": "Esraa",
                                            "ISBN": "3"
                                        },
                                        "borrower": {
                                            "id": "27b68ba2-dde6-49a5-bf7d-44352960da5e",
                                            "name": "user 1",
                                            "email": "user1@test.com"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Invalid id"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Borrowing not found",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Borrowing not found"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowings/analytics/by_month": {
            "get": {
                "tags": [
                    "Borrowings"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get analytics report of borrowing process by month",
                "parameters": [
                    {
                        "name": "month",
                        "in": "query",
                        "description": "Month (1 to 12). Defaults to the last month.",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "minimum": 1,
                            "maximum": 12
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "borrowed, returned, all, overdue. Defaults to all.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "borrowed",
                                "returned",
                                "all",
                                "overdue"
                            ]
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analytics report",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "fileUrl": "/files/analytics_report.xlsx",
                                        "count": 10,
                                        "rows": [
                                            {
                                                "id": "1b707f57-8913-4142-9d01-b0f2f893fe4f",
                                                "checkoutDate": "2024-01-11T01:40:35.977Z",
                                                "returnDate": null,
                                                "dueDate": "2024-01-11T01:50:59.883Z",
                                                "book": {
                                                    "id": "a93a8fdf-9994-456e-b120-b4e6a22385a8",
                                                    "title": "book 1",
                                                    "author": "Kafka",
                                                    "ISBN": "123"
                                                },
                                                "borrower": {
                                                    "id": "980fd826-702f-4fc4-a5bd-b81ef230b148",
                                                    "name": "user 2",
                                                    "email": "user2@test.com"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Month should be between 1 and 12"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/borrowings/analytics/by_date/{startDate}/{endDate}": {
            "get": {
                "tags": [
                    "Borrowings"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "summary": "Get analytics report of borrowing process in a specific period",
                "parameters": [
                    {
                        "name": "startDate",
                        "in": "path",
                        "description": "Start date of the period",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "date"
                        }
                    },
                    {
                        "name": "endDate",
                        "in": "path",
                        "description": "End date of the period",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "date"
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "borrowed, returned, all, overdue. Defaults to all.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "borrowed",
                                "returned",
                                "all",
                                "overdue"
                            ]
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "description": "Defaults to createdAt.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Defaults to DESC.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analytics report",
                        "content": {
                            "application/json": {
                                "example": {
                                    "data": {
                                        "fileUrl": "/files/analytics_report_period.xlsx",
                                        "count": 5,
                                        "rows": [
                                            {
                                                "id": "1b707f57-8913-4142-9d01-b0f2f893fe4f",
                                                "checkoutDate": "2024-01-11T01:40:35.977Z",
                                                "returnDate": null,
                                                "dueDate": "2024-01-11T01:50:59.883Z",
                                                "book": {
                                                    "id": "a93a8fdf-9994-456e-b120-b4e6a22385a8",
                                                    "title": "book 1",
                                                    "author": "Kafka",
                                                    "ISBN": "123"
                                                },
                                                "borrower": {
                                                    "id": "980fd826-702f-4fc4-a5bd-b81ef230b148",
                                                    "name": "user 2",
                                                    "email": "user2@test.com"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Start date should be earlier than end date"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                }
            },
            "Login": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "example": "johndoe@example.com"
                    },
                    "password": {
                        "type": "string",
                        "example": "Password123!"
                    }
                },
                "required": [
                    "email",
                    "password"
                ]
            },
            "Book": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "author": {
                        "type": "string"
                    },
                    "ISBN": {
                        "type": "string"
                    },
                    "availableQuantity": {
                        "type": "integer"
                    },
                    "shelfLocation": {
                        "type": "string"
                    }
                },
                "required": [
                    "title",
                    "author",
                    "ISBN",
                    "availableQuantity",
                    "shelfLocation"
                ]
            },
            "Borrower": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string",
                        "format": "email"
                    },
                    "password": {
                        "type": "string",
                        "format": "password"
                    }
                },
                "required": [
                    "name",
                    "email",
                    "password"
                ]
            }
        }
    }
}